apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          - name: DB_URL
            valueFrom: 
              secretKeyRef:
                name : {{ .Values.db.secretName }}
                key: DB_URL
          envFrom:
          - secretRef:
              name: {{ .Values.db.secretName }}
      imagePullSecrets: 
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
