# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres-service.app-dev.svc.cluster.local:5432/k8sdb"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"