apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # base64 인코딩된 값 (예: "postgres" → "cG9zdGdyZXM=")
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
stringData:
  DB_URL: "jdbc:postgresql://postgres-service.app-dev.svc.cluster.local:5432/k8sdb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: k8sdb
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        #emptyDir: {}   # 테스트용, 재기동 시 데이터 유지 안 됨
        persistentVolumeClaim:
          claimName: postgres-dev-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: apps-dev
spec:
  hosts:
  - "postgres-dev.k8s.dev"
  gateways:
  - istio-system/msa-gateway
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: postgres-service.apps-dev.svc.cluster.local   # 실제 Postgres 서비스 이름
        port:
          number: 5432