apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-storage
  hostPath:
    path: /kube/postgres-dev-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
  namespace: apps-dev       # 원하는 namespace
spec:
  accessModes:
    - ReadWriteOnce        # 단일 노드 읽기/쓰기
  resources:
    requests:
      storage: 500Mi         # 요청할 스토리지 용량
  storageClassName: postgres-storage  # 사용하려는 StorageClass 이름
  selector:
    matchLabels:
      app: postgres