apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /dev/jenkins-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: dev-tools       # 원하는 namespace
spec:
  accessModes:
    - ReadWriteOnce        # 단일 노드 읽기/쓰기
  resources:
    requests:
      storage: 10Gi         # 요청할 스토리지 용량
  storageClassName: manual  # 사용하려는 StorageClass 이름