image:
  pullPolicy: IfNotPresent

syncPolicy: {} # 수동배포

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prd

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
