existingConfigMap: fluent-bit-config

health:
  enabled: true
  port: 2020
  path: /api/v1/health

# fluent-bit log는 설계상 TZ를 고정하기 때문에 TZ 세팅이 의미없음
# extraEnv:
#   - name: TZ
#     value: "Asia/Seoul"

# extraVolumes:
#   - name: tz-config
#     emptyDir: {}

# extraVolumeMounts:
#   - name: tz-config
#     mountPath: /etc/localtime
#     subPath: localtime

# extraInitContainers:
#   - name: install-tzdata
#     image: busybox:1.36
#     command: ["sh", "-c"]
#     args:
#       - cp /usr/share/zoneinfo/Asia/Seoul /mounted/etc/localtime
#     volumeMounts:
#       - name: tz-config
#         mountPath: /mounted/etc